# Generated by Django 5.0.1 on 2024-02-08 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectstage',
            name='progress',
            field=models.CharField(default='0%', max_length=50),
        ),
    ]
