# Generated by Django 5.0.1 on 2024-02-08 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_alter_projectstage_progress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectstage',
            name='order',
            field=models.IntegerField(default='1'),
        ),
    ]
