# Generated by Django 5.0.1 on 2024-02-08 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_alter_projectstage_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectstage',
            name='order',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True, verbose_name='Номер этапа'),
        ),
    ]
