# Generated by Django 5.0.1 on 2024-02-08 11:55

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(default='Узбекистан', max_length=255, verbose_name='Страна')),
                ('city', models.CharField(default='Ташкент', max_length=255, verbose_name='Город')),
                ('district', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Район')),
                ('street', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Улица')),
                ('house', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Дом')),
                ('flat', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Квартира')),
                ('postal_code', models.CharField(max_length=10, verbose_name='Индекс')),
            ],
            options={
                'verbose_name': 'Адрес',
                'verbose_name_plural': 'Адреса',
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название документа')),
                ('document_type', models.CharField(choices=[('word', 'Word'), ('excel', 'Excel'), ('powerpoint', 'PowerPoint'), ('pdf', 'PDF'), ('visio', 'Visio')], max_length=20, verbose_name='Тип документа')),
                ('file', models.FileField(upload_to='documents/', verbose_name='Файл')),
            ],
            options={
                'verbose_name': 'Документ',
                'verbose_name_plural': 'Документы',
            },
        ),
        migrations.CreateModel(
            name='OwnershipForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_form', models.CharField(max_length=255, verbose_name='короткая форма')),
                ('long_form', models.CharField(max_length=255, verbose_name='длинная форма')),
            ],
            options={
                'verbose_name': 'Форма принадлежности',
                'verbose_name_plural': 'Формы принадлежности',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=255, verbose_name='Фамилия')),
                ('middle_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Отчество')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('email', models.EmailField(blank=True, max_length=255, null=True, verbose_name='Электронная почта')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Номер телефона')),
            ],
            options={
                'verbose_name': 'Персона',
                'verbose_name_plural': 'Персоны',
            },
        ),
        migrations.CreateModel(
            name='LegalEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('phoneNumber', models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator('^\\+?1?\\d{9,15}$', message='Invalid phone number')], verbose_name='Номер телефона')),
                ('websiteUrl', models.URLField(blank=True, null=True, verbose_name='ссылка на сайт')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='organizations/logos/', verbose_name='Логотип компании')),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.address', verbose_name='Адрес')),
                ('ownership_form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ownershipform', verbose_name='Форма принадлежности')),
            ],
            options={
                'verbose_name': 'Юридическое лицо',
                'verbose_name_plural': 'Юридические лица',
            },
        ),
    ]
