# Generated by Django 5.0.1 on 2024-01-22 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='tenderstage',
            name='lot',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Лот'),
        ),
    ]
